### ISSUE TITLE
/checkworld

### ISSUE THREAD

**Issue by Artistbma** [Linkupdated/LaCedule#111]
Command checks what world you are currently in. Simple.

**Comment by Artistbma** [comment]
Perhaps also a /checkworld _player_ to tell what world another player is in with the detective class. Typing the command without a player name would tell what world the player typing the command is in. However, being able to see what world another player is in should probably be discussed amongst the staff before any changes are made.

**Comment by MrSquishyDev** [comment]
Bug tracker is for finalized suggestions only.  When consensus is reached you can edit and re-open.  Please do not make reports for items that have not been discussed or agreed to by staff.
