### ISSUE TITLE
The command /lastseen is broken

### ISSUE THREAD

**Issue by austinc3** [Linkupdated/LaCedule#15]
Anyone who hasnt logged on the new map says they have last been online on December 31 1969

**Comment by Linkupdated** [comment]
it is? i didn't know that... fml

**Comment by ghost** [comment]
other dates are also wrong such as i am currently on and did /lastseen wiyo911. It says i was last on on march 8th..

**Comment by Darkirby3** [comment]
Tested on dev.
You can now use last seen to know when was the last time a player played citywars. Just a minor bug with the old member of citywars who was on the old data base system. The date risk to show 1969 due to the old timestamps.
