### ISSUE TITLE
Modify the auto messages

### ISSUE THREAD

**Issue by Linkupdated** [Linkupdated/LaCedule#28]
https://docs.google.com/spreadsheets/d/1ZS7lM_5rojl1fT391QaoWPK3uB1uA1Vcuk08gjiDHwc/edit?usp=sharing

Modify them there then i will update it

**Comment by Linkupdated** [comment]
**Anyone can update them. make them more up to date!**
Thanks

**Comment by Artistbma** [comment]
Added more, fixed issues. The current list is good to be put ingame!

**Comment by Linkupdated** [comment]
cool let me do that
