### ISSUE TITLE
/sun

### ISSUE THREAD

**Issue by ghost** [Linkupdated/LaCedule#32]
/sun doesn't always clear the rain.

**Comment by Linkupdated** [comment]
is in espicially in the hawkland world? it seems to bug there?

**Comment by Linkupdated** [comment]
chad, i need to know if its in a specific world or when is it happening?

**Comment by chaddy12** [comment]
For me, it was bugging out in the main world, but I haven't seen it bug out in a while. I let you know if I find something

**Comment by staii7** [comment]
Yea its bugged for me and a bunch of other people too in the main world, sorry was only just able to catch up with this stuff :P

**Comment by chaddy12** [comment]
k sometimes it works for me during the daytime irl , but when I get on at night (around 12am mountain time) it seems to glitch out in the main world ill upload some screenies see if that helps. I have no idea why it glitches out!! Its making me pull my hair out
![2015-04-25_01 01 06](https://cloud.githubusercontent.com/assets/11859130/7331989/77f1a646-eae7-11e4-8e0e-b6fa5ea574d4.png)
![2015-04-25_01 01 21](https://cloud.githubusercontent.com/assets/11859130/7331990/77f6a20e-eae7-11e4-94f2-d31270f82c39.png)
![2015-04-25_01 01 28](https://cloud.githubusercontent.com/assets/11859130/7331991/77f627fc-eae7-11e4-9ab3-4a4a0f4491f2.png)
![2015-04-25_01 05 26](https://cloud.githubusercontent.com/assets/11859130/7331992/77f6fcb8-eae7-11e4-9e7f-913c1a87529f.png)

during the morning irl for me it works fine !  I dont get it!!

**Comment by MrSquishyDev** [comment]
Should be fixed.  Reopen if not.
