### ISSUE TITLE
No Sponges in Chunkwars!

### ISSUE THREAD

**Issue by Artistbma** [Linkupdated/LaCedule#37]
Apparently there is an issue during chunkwars that causes one side to be unable to place sponges while the other side can. This is fairly important, considering this basically wins the chunkwar for the side that CAN place sponges.

**Comment by Linkupdated** [comment]
wierd, i will look into that with dark.

**Comment by Linkupdated** [comment]
If you have more informations you can post them here! Thanks

**Comment by Linkupdated** [comment]
Guys i will need more information on this one, like is placing but not creating the beacon or just not placing.

If not placing this means he is not placing the sponge in a war chunk. Please check it up! thanks

**Comment by Linkupdated** [comment]
bug was not found again
