### ISSUE TITLE
Bazaar Forum Section

### ISSUE THREAD

**Issue by Artistbma** [Linkupdated/LaCedule#38]
A forum section for selling items. Could be called "The Bazaar" or "The Marketplace".

**Comment by Linkupdated** [comment]
That could be great but there are chances we fix and bring back the Itemshop. Would it be a good idea?

**Comment by Artistbma** [comment]
There are still some people who would like the "old fashioned" way of selling and buying items with actually talking with someone else. I think it'd be good if we added both.

**Comment by Linkupdated** [comment]
nice! ima do that asap!

**Comment by Linkupdated** [comment]
I need you to test if the section permission is working properly, otherwise its added!
