### ISSUE TITLE
Ghost race

### ISSUE THREAD

**Issue by chaddy12** [Linkupdated/LaCedule#41]
Ghost race is super buggy. When you are a ghost if you click on anything it treats you like you are shifting so you cant click on furnaces chests ect with any thing on your hand, if you do it just places the block. Also, when you are a ghost and switch your race, to other players you are still shown as shifting. This might cause problems with people blaming others for hacks. 

I think we can switch up ghost race abit it make it more relevant. Maybe we can have it if you eat a item, like golden carrot or something of worth, you get the potion effect to become  invisible for like 1 min. Could be more useful!

**Comment by Linkupdated** [comment]
good idea. I think i will remove the sneak system. Too much problems seems to occur with it.

We will replace it like something you said!
