### ISSUE TITLE
Citizen Notification

### ISSUE THREAD

**Issue by Artistbma** [Linkupdated/LaCedule#45]
When a citizen in your city logs on, broadcast a message to all other online citizens saying that they have logged on. Would work similar to the friend logon notification, and would be green instead of cyan.

**Comment by Linkupdated** [comment]
done! this will need testing when i push it out

**Comment by Darkirby3** [comment]
Tested on dev.
Now every time you connect all your citizen have a notification that you connect online.

**Comment by Artistbma** [comment]
Change cyan words in the notification to &2 green, to distinguish it from Friend Notification more.

**Comment by Linkupdated** [comment]
changed to &a
