### ISSUE TITLE
Set First Spawn to /tut

### ISSUE THREAD

**Issue by Artistbma** [Linkupdated/LaCedule#48]
Make it so when players first join the server, they automatically spawn at /tut.

**Comment by ghost** [comment]
Only been suggested around 507 times.

**Comment by Linkupdated** [comment]
@wiyo911 but it never have been here.

**Comment by Linkupdated** [comment]
@Darkirby3 is not sure if its a good idea. So i don't know.

**Comment by Darkirby3** [comment]
I don't want our new member geting stuck in a room full of sign. Also the first impression is one of the most important thing that make a player stay or not. When you spawn at ospawn you see many player running and it look alive. Spawning inside a empty room full of sign is not interesting and i know this should help our news member to be more informed about what citywars is but i think it will only result in more player quit the server before even knowing what do the server.
