### ISSUE TITLE
Bows

### ISSUE THREAD

**Issue by ghost** [Linkupdated/LaCedule#64]
Bows don’t damage people at random times. Not sure why.

**Comment by Linkupdated** [comment]
If i don't have more information i can't fix it. Im not a magician

**Comment by chaddy12** [comment]
ive seen this happen before and tried to recreate it but havent had any luck, ill keep trying

**Comment by Linkupdated** [comment]
test

**Comment by MrSquishyDev** [comment]
Insufficient information.  Re-open if more info available.
