### ISSUE TITLE
Hawkland Entrances

### ISSUE THREAD

**Issue by chaddy12** [Linkupdated/LaCedule#73]
What if we made the chunks right next to the ospawn chunks at hawkland the pvp pit chunks? so people cant build around the entrances. It would stop nerds building stairs back up into the spawn, and letting mobs in, also blocking off any building around the spawn so people can get in and out without any trouble
![2015-04-22_18 09 41](https://cloud.githubusercontent.com/assets/11859130/7288173/fc0f67c0-e91a-11e4-866e-9ea94be116c5.png)

**Comment by Linkupdated** [comment]
dark will be working on it soon.

**Comment by Linkupdated** [comment]
dark fixed it!
