### ISSUE TITLE
Mechanic Bug

### ISSUE THREAD

**Issue by staii7** [Linkupdated/LaCedule#74]
http://citywars.ca/forum/12/3068-1

**Comment by Linkupdated** [comment]
Mechanic work as intended, but it heals you of .2HP that's why you don't see the changes everytimes

**Comment by staii7** [comment]
Maybe make it so that it doesn't use up iron ingots when you don't actually get healed?

**Comment by staii7** [comment]
Ooo I understand, my bad :P

**Comment by Linkupdated** [comment]
ok what do you guys propose for this race instead of healing?

**Comment by Linkupdated** [comment]
mouahaaha, chad find something to replace mechanic's ability xD

**Comment by chaddy12** [comment]
Change it where if you eat a Iron block you get the potion effect absorption for say like 10 seconds with a minute cooldown? I remember you said you dont like cooldowns :P So if not ill try and think of something else

**Comment by Darkirby3** [comment]
- [x] Change right click for left click because everytime you try to use your ability you also place a block on the ground.
- [x] Change the race description for something like :
  Left click on a iron block to gain 2 heart for 10 sec.

**Comment by Linkupdated** [comment]
done! and tested
