### ISSUE TITLE
City voting bugged

### ISSUE THREAD

**Issue by ghost** [Linkupdated/LaCedule#79]
Voting for your city takes a while to register and sometimes does not at all. I would also remove the 'comment' section and numbers such that one could simply vote their city up by 1 nothing else.

**Comment by ghost** [comment]
My votes dont even register even after hours and hours.

**Comment by Linkupdated** [comment]
its once per day at around 4am

<div>-------- Message d'origine --------</div><div>De : wiyo911 <notifications@github.com> </div><div>Date :04/24/2015  15:57  (GMT-05:00) </div><div>À : Linkupdated/LaCedule <LaCedule@noreply.github.com> </div><div>Objet : Re: [LaCedule] City voting bugged (#79) </div><div>
</div>

My votes dont even register even after hours and hours.

---
