### ISSUE TITLE
Reduce Mob Spawns in Hawkland

### ISSUE THREAD

**Issue by Artistbma** [Linkupdated/LaCedule#88]
More mobs are spawning than are being used in Hawkland. The surplus of mobs in Hawkland sort of takes away from the point of it (for PvP). I'm not saying remove mobs from Hawkland completely. Just, maybe reduce the frequency of mob spawns to 50-75% of what it is now.

**Comment by Linkupdated** [comment]
limit to 250 instead of 500.
