### ISSUE TITLE
City portal

### ISSUE THREAD

**Issue by chaddy12** [Linkupdated/LaCedule#93]
City portal in Athens only one portal works
![2015-04-26_17 11 19](https://cloud.githubusercontent.com/assets/11859130/7339770/bf2c6bee-ec37-11e4-9374-42c9e06afc9a.png)
![2015-04-26_17 11 40](https://cloud.githubusercontent.com/assets/11859130/7339769/bf2be642-ec37-11e4-81f0-88c9846ed2c3.png)

the second portal, if you go back into it, it just tps you into the ground

I told them just to buy a new one and see if that fixes it, but not sure what caused it

**Comment by Linkupdated** [comment]
wierd... If you have more info on that tell me!
