### ISSUE TITLE
Scholar Class

### ISSUE THREAD

**Issue by Artistbma** [Linkupdated/LaCedule#95]
https://docs.google.com/document/d/1qFaJzLzln0fWVprIX39A1SDuR9Nb-aynMzgOrC9YKVg/mobilebasic?pli=1

**Comment by Linkupdated** [comment]
really good idéal!

<div>-------- Message d'origine --------</div><div>De : Artistbma <notifications@github.com> </div><div>Date :04/27/2015  19:11  (GMT-05:00) </div><div>À : Linkupdated/LaCedule <LaCedule@noreply.github.com> </div><div>Objet : [LaCedule] Scholar Class (#95) </div><div>
</div>

https://docs.google.com/document/d/1qFaJzLzln0fWVprIX39A1SDuR9Nb-aynMzgOrC9YKVg/mobilebasic?pli=1

---

Reply to this email directly or view it on GitHub:
https://github.com/Linkupdated/LaCedule/issues/95

**Comment by Artistbma** [comment]
Addition made to the doc to reduce possibility of abusing the class's ability and economic destruction. :P

**Comment by Linkupdated** [comment]
cool!! : P

**Comment by Linkupdated** [comment]
done!
